# Calamares fstab module
---
# Mount options for various filesystems
mountOptions:
    btrfs: defaults,noatime,compress=zstd:1,space_cache=v2,subvol=@
    ext4:  defaults,noatime
    xfs:   defaults,noatime
    vfat:  defaults,utf8
    exfat: defaults,utf8
    f2fs:  defaults,noatime

# ssdExtraMountOptions for solid-state drives
ssdExtraMountOptions:
    btrfs: ssd,commit=120

# Recommended options for /home on btrfs
btrfsSubvolumes:
    - mountPoint: /
      subvolume:  @
    - mountPoint: /home
      subvolume:  @home
    - mountPoint: /var/cache
      subvolume:  @cache
    - mountPoint: /var/log
      subvolume:  @log
