# Calamares mount module
---
# Where the target root is mounted (Calamares fills this in dynamically)
mountPoint: /tmp/calomount

# Use extra partitions for /home, /boot etc if the user created them
extraMounts:
    - device: proc
      fs: proc
      mountPoint: /proc
    - device: sys
      fs: sysfs
      mountPoint: /sys
    - device: /dev
      fs: none
      mountPoint: /dev
      options: bind
    - device: /dev/run
      fs: none
      mountPoint: /run
      options: bind
    - device: /run/novatos/bootmnt
      fs: none
      mountPoint: /run/novatos/bootmnt
      options: bind

extraMountsEfi:
    - device: efivarfs
      fs: efivarfs
      mountPoint: /sys/firmware/efi/efivars
