# Calamares partition module
---
userSwapChoices:
    - none      # No swap
    - small     # ~RAM/4
    - suspend   # = RAM (for hibernate)
    - file      # swapfile

# Always show swap choices even on machines with no detected swap
neverCreateSwap: false

# Correctly draw the partitioning module as the only step in the partitioning page
drawNestedPartitions: true

# Default filesystem for new partitions
defaultFileSystemType: "btrfs"

# Allow enabling swap inside LUKS
enableLuksSwapEncryption: true

# Allow manual partitioning
allowManualPartitioning: true

# Initial partitioning choice (one of: none / erase / replace / alongside / manual)
initialPartitioningChoice: erase

# Initial swap choice
initialSwapChoice: suspend

# Required partition table types
requiredPartitionTableType:
    - gpt
    - msdos
