# Calamares finished module
---
# Restart now? Show a button in the finished page
restartNow: false

# Notify on install complete (use plasma-notify if available)
notifyOnFinished: false

# Whether to ask for confirmation when "Done" is clicked
confirmation: true
