# Calamares locale module
---
# Use GeoIP to pre-select locale
region: "America"
zone:   "New_York"

# GeoIP config
geoip:
    style:    "json"
    url:      "https://ipapi.co/json/"
    selector: "timezone"
