# Calamares services-systemd module
---
# Services to enable on the installed system
services:
    - name: "NetworkManager"
      action: enable
    - name: "sddm"
      action: enable
    - name: "bluetooth"
      action: enable
    - name: "cups"
      action: enable
    - name: "cups.socket"
      action: enable
    - name: "avahi-daemon"
      action: enable
    - name: "avahi-daemon.socket"
      action: enable
    - name: "firewalld"
      action: enable
    - name: "libvirtd"
      action: enable
    - name: "docker"
      action: enable
    - name: "systemd-resolved"
      action: enable
    - name: "systemd-timesyncd"
      action: enable
    - name: "haveged"
      action: enable
    - name: "reflector.timer"
      action: enable
    - name: "fwupd"
      action: enable
    - name: "power-profiles-daemon"
      action: enable
    - name: "tlp"
      action: disable   # conflicts with power-profiles-daemon
