# Calamares welcome module
---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    false

requirements:
    requiredStorage:    12          # GiB
    requiredRam:        2           # GiB
    internetCheck:      true
    root:
        required:       true
    screen:
        required:       true

required:
    - storage
    - ram
    - root

# URLs
supportUrl:             "https://github.com/salom600/NovatOS/issues"
knownIssuesUrl:         "https://github.com/salom600/NovatOS/issues"
