# NovatOS Install — boot to graphical installer
# Uses nomodeset for universal GPU compatibility.

title    NovatOS Install
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-zen
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-zen.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% quiet loglevel=3 nomodeset systemd.unit=graphical.target novatos.install=1
