# NovatOS Live (NVIDIA mode) — blacklists nouveau for systems with NVIDIA dGPUs
title    NovatOS Live (NVIDIA, blacklist nouveau)
sort-key 03
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-zen
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-zen.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% quiet splash loglevel=3 modprobe.blacklist=nouveau
