# NovatOS Live (Safe graphics) — nomodeset for display issues, Ventoy grub2 mode
title    NovatOS Live (Safe graphics, nomodeset)
sort-key 04
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-zen
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-zen.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% quiet loglevel=3 nomodeset 3
