[Autologin]
User=novatos
Session=plasma.desktop

[Theme]
ThemeDir=/usr/share/sddm/themes
Current=novatos
CursorTheme=breeze_cursors

[Users]
MaximumUid=60000
MinimumUid=1000
HideUsers=
RememberLastUser=true
RememberLastSession=true

[Wayland]
EnableHiDPI=true
CompositorCommand=kwin_wayland --no-lockscreen
DisplayCommand=/usr/share/sddm/scripts/wayland-session
SessionDir=/usr/share/wayland-sessions

[X11]
EnableHiDPI=true
ServerArguments=-nolisten tcp
DisplayCommand=/usr/share/sddm/scripts/Xsetup
DisplayStopCommand=/usr/share/sddm/scripts/Xstop
SessionDir=/usr/share/xsessions
