# systemd-boot loader config for NovatOS UEFI
# timeout = seconds to show the boot menu before booting the default entry
# default = filename of the entry to boot by default (without the path)
# The menu will show ALL .conf files in the entries/ directory.

timeout  15
default  01-novatos-zen.conf
beep     on
console-mode max
editor   no
