# NovatOS Calamares main config
# =============================
# Standard modules in install order. Branded with the NovatOS look.

modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - luksopenswaphookcfg
      - luksbootkeyfile
      - initcpiocfg
      - initcpio
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - bootloader
      - packages
      - luksbootkeyfile
      - plymouthcfg
      - initramfs
      - removeuser
      - remove-temporary-files
      - contextmenu
      - shellprocess
  - show:
      - finished

# Branding
branding: novatos

# Show / don't show debug window
show-debug: false

# Don't quit on cancel
dont-chroot: false

# Oem mode disabled
oem-setup: false

# Disable cancel during install
cancel-at-finish: false
